// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Product _$ProductFromJson(Map<String, dynamic> json) => Product(
  id: json['id'] as String,
  title: json['title'] as String,
  description: json['description'] as String,
  images: (json['images'] as List<dynamic>).map((e) => e as String).toList(),
  categoryId: json['categoryId'] as String,
  catname: json['catname'] as String,
  category: Category.fromJson(json['category'] as Map<String, dynamic>),
  parentCategoryId: json['parentCategoryId'] as String?,
  parentCategoryName: json['parentCategoryName'] as String?,
  grandParentCategoryId: json['grandParentCategoryId'] as String?,
  grandParentCategoryName: json['grandParentCategoryName'] as String?,
  mainCategoryId: json['mainCategoryId'] as String?,
  mainCategoryName: json['mainCategoryName'] as String?,
  subCategoryId: json['subCategoryId'] as String?,
  subCategoryName: json['subCategoryName'] as String?,
  subSubCategoryId: json['subSubCategoryId'] as String?,
  subSubCategoryName: json['subSubCategoryName'] as String?,
  subSubSubCategoryId: json['subSubSubCategoryId'] as String?,
  subSubSubCategoryName: json['subSubSubCategoryName'] as String?,
  condition: json['condition'] as String,
  brand: json['brand'] as String?,
  model: json['model'] as String?,
  estimatedValue: (json['estimatedValue'] as num?)?.toDouble(),
  ownerId: json['ownerId'] as String,
  owner: User.fromJson(json['owner'] as Map<String, dynamic>),
  tradePreferences: (json['tradePreferences'] as List<dynamic>)
      .map((e) => e as String)
      .toList(),
  status: $enumDecode(_$ProductStatusEnumMap, json['status']),
  cityId: json['cityId'] as String,
  cityTitle: json['cityTitle'] as String,
  districtId: json['districtId'] as String,
  districtTitle: json['districtTitle'] as String,
  createdAt: DateTime.parse(json['createdAt'] as String),
  updatedAt: DateTime.parse(json['updatedAt'] as String),
  expiresAt: json['expiresAt'] == null
      ? null
      : DateTime.parse(json['expiresAt'] as String),
  productImage: json['productImage'] as String?,
  productGallery: (json['productGallery'] as List<dynamic>?)
      ?.map((e) => e as String)
      .toList(),
  productCondition: json['productCondition'] as String?,
  tradeFor: json['tradeFor'] as String?,
  categoryList: (json['categoryList'] as List<dynamic>?)
      ?.map((e) => Category.fromJson(e as Map<String, dynamic>))
      .toList(),
  userFullname: json['userFullname'] as String?,
  userFirstname: json['userFirstname'] as String?,
  userLastname: json['userLastname'] as String?,
  userPhone: json['userPhone'] as String?,
  userImage: json['userImage'] as String?,
  proView: json['proView'] as String?,
  isShowContact: json['isShowContact'] as bool?,
  isFavorite: json['isFavorite'] as bool?,
  isSponsor: json['isSponsor'] as bool?,
  isTrade: json['isTrade'] as bool?,
  productLat: json['productLat'] as String?,
  productLong: json['productLong'] as String?,
  productCode: json['productCode'] as String?,
  favoriteCount: (json['favoriteCount'] as num?)?.toInt(),
  profilePhoto: json['profilePhoto'] as String?,
  shareLink: json['shareLink'] as String?,
);

Map<String, dynamic> _$ProductToJson(Product instance) => <String, dynamic>{
  'id': instance.id,
  'title': instance.title,
  'description': instance.description,
  'images': instance.images,
  'categoryId': instance.categoryId,
  'catname': instance.catname,
  'category': instance.category,
  'parentCategoryId': instance.parentCategoryId,
  'parentCategoryName': instance.parentCategoryName,
  'grandParentCategoryId': instance.grandParentCategoryId,
  'grandParentCategoryName': instance.grandParentCategoryName,
  'mainCategoryId': instance.mainCategoryId,
  'mainCategoryName': instance.mainCategoryName,
  'subCategoryId': instance.subCategoryId,
  'subCategoryName': instance.subCategoryName,
  'subSubCategoryId': instance.subSubCategoryId,
  'subSubCategoryName': instance.subSubCategoryName,
  'subSubSubCategoryId': instance.subSubSubCategoryId,
  'subSubSubCategoryName': instance.subSubSubCategoryName,
  'condition': instance.condition,
  'brand': instance.brand,
  'model': instance.model,
  'estimatedValue': instance.estimatedValue,
  'ownerId': instance.ownerId,
  'owner': instance.owner,
  'tradePreferences': instance.tradePreferences,
  'cityId': instance.cityId,
  'cityTitle': instance.cityTitle,
  'districtId': instance.districtId,
  'districtTitle': instance.districtTitle,
  'status': _$ProductStatusEnumMap[instance.status]!,
  'createdAt': instance.createdAt.toIso8601String(),
  'updatedAt': instance.updatedAt.toIso8601String(),
  'expiresAt': instance.expiresAt?.toIso8601String(),
  'productImage': instance.productImage,
  'productGallery': instance.productGallery,
  'productCondition': instance.productCondition,
  'tradeFor': instance.tradeFor,
  'categoryList': instance.categoryList,
  'userFullname': instance.userFullname,
  'userFirstname': instance.userFirstname,
  'userLastname': instance.userLastname,
  'userPhone': instance.userPhone,
  'userImage': instance.userImage,
  'proView': instance.proView,
  'isShowContact': instance.isShowContact,
  'isFavorite': instance.isFavorite,
  'isSponsor': instance.isSponsor,
  'isTrade': instance.isTrade,
  'productLat': instance.productLat,
  'productLong': instance.productLong,
  'productCode': instance.productCode,
  'favoriteCount': instance.favoriteCount,
  'profilePhoto': instance.profilePhoto,
  'shareLink': instance.shareLink,
};

const _$ProductStatusEnumMap = {
  ProductStatus.active: 'active',
  ProductStatus.inactive: 'inactive',
  ProductStatus.traded: 'traded',
  ProductStatus.expired: 'expired',
  ProductStatus.deleted: 'deleted',
};

Category _$CategoryFromJson(Map<String, dynamic> json) => Category(
  id: json['id'] as String,
  name: json['name'] as String,
  icon: json['icon'] as String,
  parentId: json['parentId'] as String?,
  parentName: json['parentName'] as String?,
  grandParentId: json['grandParentId'] as String?,
  grandParentName: json['grandParentName'] as String?,
  mainCategoryId: json['mainCategoryId'] as String?,
  mainCategoryName: json['mainCategoryName'] as String?,
  subCategoryId: json['subCategoryId'] as String?,
  subCategoryName: json['subCategoryName'] as String?,
  children: (json['children'] as List<dynamic>?)
      ?.map((e) => Category.fromJson(e as Map<String, dynamic>))
      .toList(),
  isActive: json['isActive'] as bool,
  order: (json['order'] as num).toInt(),
  level: (json['level'] as num?)?.toInt() ?? 1,
);

Map<String, dynamic> _$CategoryToJson(Category instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'icon': instance.icon,
  'parentId': instance.parentId,
  'parentName': instance.parentName,
  'grandParentId': instance.grandParentId,
  'grandParentName': instance.grandParentName,
  'mainCategoryId': instance.mainCategoryId,
  'mainCategoryName': instance.mainCategoryName,
  'subCategoryId': instance.subCategoryId,
  'subCategoryName': instance.subCategoryName,
  'children': instance.children,
  'isActive': instance.isActive,
  'order': instance.order,
  'level': instance.level,
};
