// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************


Map<String, dynamic> _$ProductToJson(Product instance) => <String, dynamic>{
  'id': instance.id,
  'title': instance.title,
  'description': instance.description,
  'images': instance.images,
  'categoryId': instance.categoryId,
  'catname': instance.catname,
  'category': instance.category,
  'parentCategoryId': instance.parentCategoryId,
  'parentCategoryName': instance.parentCategoryName,
  'grandParentCategoryId': instance.grandParentCategoryId,
  'grandParentCategoryName': instance.grandParentCategoryName,
  'mainCategoryId': instance.mainCategoryId,
  'mainCategoryName': instance.mainCategoryName,
  'subCategoryId': instance.subCategoryId,
  'subCategoryName': instance.subCategoryName,
  'subSubCategoryId': instance.subSubCategoryId,
  'subSubCategoryName': instance.subSubCategoryName,
  'subSubSubCategoryId': instance.subSubSubCategoryId,
  'subSubSubCategoryName': instance.subSubSubCategoryName,
  'condition': instance.condition,
  'brand': instance.brand,
  'model': instance.model,
  'estimatedValue': instance.estimatedValue,
  'ownerId': instance.ownerId,
  'owner': instance.owner,
  'tradePreferences': instance.tradePreferences,
  'cityId': instance.cityId,
  'cityTitle': instance.cityTitle,
  'districtId': instance.districtId,
  'districtTitle': instance.districtTitle,
  'status': _$ProductStatusEnumMap[instance.status]!,
  'createdAt': instance.createdAt.toIso8601String(),
  'updatedAt': instance.updatedAt.toIso8601String(),
  'expiresAt': instance.expiresAt?.toIso8601String(),
  'productImage': instance.productImage,
  'productGallery': instance.productGallery,
  'productCondition': instance.productCondition,
  'tradeFor': instance.tradeFor,
  'categoryList': instance.categoryList,
  'userFullname': instance.userFullname,
  'userFirstname': instance.userFirstname,
  'userLastname': instance.userLastname,
  'userPhone': instance.userPhone,
  'userImage': instance.userImage,
  'proView': instance.proView,
  'isShowContact': instance.isShowContact,
  'isFavorite': instance.isFavorite,
  'isSponsor': instance.isSponsor,
  'sponsorUntil': instance.sponsorUntil,
  'isTrade': instance.isTrade,
  'productLat': instance.productLat,
  'productLong': instance.productLong,
  'productCode': instance.productCode,
  'favoriteCount': instance.favoriteCount,
  'profilePhoto': instance.profilePhoto,
  'shareLink': instance.shareLink,
  'averageRating': instance.averageRating,
  'totalReviews': instance.totalReviews,
};

const _$ProductStatusEnumMap = {
  ProductStatus.active: 'active',
  ProductStatus.inactive: 'inactive',
  ProductStatus.traded: 'traded',
  ProductStatus.expired: 'expired',
  ProductStatus.deleted: 'deleted',
};


Map<String, dynamic> _$CategoryToJson(Category instance) => <String, dynamic>{
  'id': instance.id,
  'name': instance.name,
  'icon': instance.icon,
  'parentId': instance.parentId,
  'parentName': instance.parentName,
  'grandParentId': instance.grandParentId,
  'grandParentName': instance.grandParentName,
  'mainCategoryId': instance.mainCategoryId,
  'mainCategoryName': instance.mainCategoryName,
  'subCategoryId': instance.subCategoryId,
  'subCategoryName': instance.subCategoryName,
  'children': instance.children,
  'isActive': instance.isActive,
  'order': instance.order,
  'level': instance.level,
};
