// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKi57Bz_bVhatbYuycX_UVmeRJ8GSKggw',
    appId: '1:422264804561:web:850fb998688d1b58ce61f0',
    messagingSenderId: '422264804561',
    projectId: 'takasla-b2aa5',
    authDomain: 'takasla-b2aa5.firebaseapp.com',
    databaseURL: 'https://takasla-b2aa5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takasla-b2aa5.firebasestorage.app',
    measurementId: 'G-BFQQ20VFLK',
  );

  // Bu değerleri Firebase Console'dan almanız gerekiyor

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrF93iVesLFoTpDXBQG6ILnd_Z1B7jeI4',
    appId: '1:422264804561:android:f051979faf48e8e2ce61f0',
    messagingSenderId: '422264804561',
    projectId: 'takasla-b2aa5',
    databaseURL: 'https://takasla-b2aa5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takasla-b2aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3MaXvP6uCEt9FsgVe-1GasluEFTypXo',
    appId: '1:422264804561:ios:05775d50977f383ece61f0',
    messagingSenderId: '422264804561',
    projectId: 'takasla-b2aa5',
    databaseURL: 'https://takasla-b2aa5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'takasla-b2aa5.firebasestorage.app',
    iosBundleId: 'com.rivorya.takaslyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
    iosClientId: 'your-ios-client-id',
    iosBundleId: 'com.rivorya.takaslyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-api-key',
    appId: 'your-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    databaseURL: 'https://your-project-id-default-rtdb.firebaseio.com',
    storageBucket: 'your-project-id.appspot.com',
  );
} 